# Generated by Django 2.2.3 on 2019-07-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_spot_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='message',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
