# Generated by Django 2.2.3 on 2019-07-31 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spots', '0003_auto_20190729_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='buyer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spots', to=settings.AUTH_USER_MODEL),
        ),
    ]
